export const homeSiderActionsTypes = {
    HOME_GET_NAV: "HOME_GET_NAV",
    HOME_GET_NAV_SUCCESS: "HOME_GET_NAV_SUCCESS",
}


export const homeArticleActionsTypes = {
    HOME_GET_ARTICLES: "HOME_GET_ARTICLES",
    HOME_GET_ARTICLES_SUCCESS: "HOME_GET_ARTICLES_SUCCESS",
    HOME_GET_ARTICLES_DETAIL: "HOME_GET_ARTICLES_DETAIL",
    HOME_GET_ARTICLES_DETAIL_SUCCESS: "HOME_GET_ARTICLES_DETAIL_SUCCESS",
}

export const userActionTypes={
    USER_LOGIN:"USER_LOGIN",
    USER_GET:"USER_GET"
}

export const globalActionsTypes = {
    FETCH_START: "FETCH_START",
    FETCH_END: "FETCH_END",
}